<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllOrdered()
    {
         $qb = $this->createQueryBuilder('cat')
            ->addOrderBy('cat.name', 'DESC');
         $this->joinFc($qb);
          return  $qb->getQuery()
            ->execute();
    }


    private function joinFc($qb){
        $qb->leftJoin('cat.fortuneCookies','fc')
            ->addSelect('fc');

    }


    public function search($searchTerm)
    {
        return $this->createQueryBuilder('cat')
            ->leftJoin('cat.fortuneCookies','fc')
            ->andWhere('cat.name like :searchTerm OR cat.iconKey LIKE :searchTerm  OR fc.fortune like :searchTerm ')
            ->setParameter('searchTerm','%'. $searchTerm.'%')
            ->addSelect('fc')
            ->getQuery()
            ->execute();
    }
}
