<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FortuneCookieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FortuneCookieRepository extends EntityRepository
{
    public function calculateSum(Category $category)
    {
        return $this->createQueryBuilder('fc')->select('SUM(fc.numberPrinted) as fortunesPrinted')->getQuery()->getSingleScalarResult();
    }
}
